version: '2.3'

services:
  crack_classification_service:
    container_name: crack_classification_service
    runtime: nvidia
    image: tensorflow/serving:latest-gpu
    restart: always
    ports:
      - "8501:8501"
    volumes:
      - ./models:/models/
    environment:
      - MODEL_NAME=simplenet_cracks8020
      - NVIDIA_VISIBLE_DEVICES=all
    networks:
      - cracks

networks:
  cracks:
    driver: bridge


